"""Generate a key-value-modded-strings-utf8.txt for AoE2:DE hotkey mods.

Reads custom .hkp hotkey files and produces the IDS_MOD_TTS_VISIBLE_HOTKEYS
entries that control the key labels shown on the in-game command grid:

    | 01 | 02 | 03 | 04 | 05 |
    | 06 | 07 | 08 | 09 | 10 |
    | 11 | 12 | 13 | 14 | 15 |

By default, labels are generated for the Economic Build Menu. Use --panel
to target a specific panel, or --best-fit to pick the most common key per
position across all command-grid panels.

Run from ``src/``:
    python -m hotkeys.hkp.keys_for_language Base.hkp [Profile.hkp] [-o output.txt]
    python -m hotkeys.hkp.keys_for_language Base.hkp --panel "Military Build Menu"
    python -m hotkeys.hkp.keys_for_language Base.hkp Profile.hkp --best-fit
    python -m hotkeys.hkp.keys_for_language --list-panels
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional

if __package__ in (None, ""):
    _here = os.path.dirname(os.path.abspath(__file__))
    _src = os.path.abspath(os.path.join(_here, "..", ".."))
    if _src not in sys.path:
        sys.path.insert(0, _src)
    from hotkeys.hkp.new_hotkey_file import HotkeyFile  # type: ignore
    from hotkeys.hkp.parse import FileType  # type: ignore
    from hotkeys.hkp.strings import hk_groups  # type: ignore
else:
    from .new_hotkey_file import HotkeyFile
    from .parse import FileType
    from .strings import hk_groups

# Panels whose hotkeys map to the 5x3 command grid (up to 15 slots each).
GRID_PANELS = [
    "Economic Build Menu",
    "Military Build Menu",
    "Villagers",
    "Military Units",
    "Town Center",
    "Dock",
    "Barracks",
    "Archery Range",
    "Stable",
    "Siege Workshop",
    "Monastery",
    "Market",
    "Castle",
    "Mill",
    "Mining Camp",
    "Lumber Camp",
    "Blacksmith",
    "University",
]

DEFAULT_PANEL = "Economic Build Menu"

# AoE2 virtual-key-code → display label for the mod overlay.
KEYCODE_LABELS: Dict[int, str] = {
    0: "",
    8: "Bksp", 9: "Tab", 13: "Enter", 16: "Shift", 17: "Ctrl", 18: "Alt",
    19: "Pause", 20: "Caps", 27: "Esc", 32: "Space",
    33: "PgUp", 34: "PgDn", 35: "End", 36: "Home",
    37: "Left", 38: "Up", 39: "Right", 40: "Down",
    44: "PrtSc", 45: "Ins", 46: "Del",
    91: "LWin", 92: "RWin", 93: "Menu",
    96: "Num0", 97: "Num1", 98: "Num2", 99: "Num3", 100: "Num4",
    101: "Num5", 102: "Num6", 103: "Num7", 104: "Num8", 105: "Num9",
    106: "Num*", 107: "Num+", 108: "Num,", 109: "Num-", 110: "Num.", 111: "Num/",
    112: "F1", 113: "F2", 114: "F3", 115: "F4", 116: "F5", 117: "F6",
    118: "F7", 119: "F8", 120: "F9", 121: "F10", 122: "F11", 123: "F12",
    144: "NumLk", 145: "ScrLk",
    186: ";", 187: "=", 188: ",", 189: "-", 190: ".", 191: "/", 192: "`",
    219: "[", 220: "\\", 221: "]", 222: "'",
    251: "XBtn2", 252: "XBtn1", 253: "MBtn", 254: "WhlDn", 255: "WhlUp",
}


def keycode_to_label(code: int) -> str:
    if code in KEYCODE_LABELS:
        return KEYCODE_LABELS[code]
    if 48 <= code <= 57:
        return chr(code)
    if 65 <= code <= 90:
        return chr(code)
    return f"0x{code:02X}"


def detect_file_type(name: str) -> FileType:
    return FileType.HKP if Path(name).stem.lower() == "base" else FileType.HKI


def load_hotkeys(paths: List[str]) -> Dict[int, int]:
    """Load hotkey files and return {string_id: keycode} for all hotkeys."""
    sid_to_keycode: Dict[int, int] = {}
    for p in paths:
        ftype = detect_file_type(p)
        with open(p, "rb") as f:
            hf = HotkeyFile(f.read(), False, Path(p).name, ftype)
        for _key, entry in hf.data.items():
            sid_to_keycode[entry["string_id"]] = entry["keycode"]
    return sid_to_keycode


def get_panel_keycodes(sid_to_keycode: Dict[int, int],
                       panel: str) -> List[int]:
    """Return the keycodes for each grid position (0-14) of a panel."""
    ids = hk_groups.get(panel, [])
    return [sid_to_keycode.get(ids[i], 0) if i < len(ids) else 0
            for i in range(15)]


def get_best_fit_keycodes(sid_to_keycode: Dict[int, int]) -> List[int]:
    """For each grid position, pick the most common keycode across all panels."""
    result = []
    for pos in range(15):
        votes: Counter = Counter()
        for panel in GRID_PANELS:
            ids = hk_groups.get(panel, [])
            if pos < len(ids):
                code = sid_to_keycode.get(ids[pos], 0)
                if code != 0:
                    votes[code] += 1
        result.append(votes.most_common(1)[0][0] if votes else 0)
    return result


HEADER_TEMPLATE = """\
//
// Generated by: python -m hotkeys.hkp.keys_for_language
// Panel: {panel}
//
// Grid layout:
//  | 01 | 02 | 03 | 04 | 05 |
//  | 06 | 07 | 08 | 09 | 10 |
//  | 11 | 12 | 13 | 14 | 15 |
//
// Edit values in "" to change displayed keys. Set to "" to hide a key.
//
"""


def generate(paths: List[str], panel: str = DEFAULT_PANEL,
             best_fit: bool = False) -> str:
    sid_to_keycode = load_hotkeys(paths)

    if best_fit:
        keycodes = get_best_fit_keycodes(sid_to_keycode)
        panel_label = "Best Fit (all panels)"
    else:
        keycodes = get_panel_keycodes(sid_to_keycode, panel)
        panel_label = panel

    lines = [HEADER_TEMPLATE.format(panel=panel_label)]
    for i, code in enumerate(keycodes):
        label = keycode_to_label(code)
        lines.append(f'IDS_MOD_TTS_VISIBLE_HOTKEYS_{i + 1:02d} "{label}"')
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m hotkeys.hkp.keys_for_language",
        description="Generate key-value-modded-strings-utf8.txt from custom .hkp files.",
    )
    p.add_argument("files", nargs="*",
                    help="One or more .hkp files (Base.hkp and/or profile)")
    p.add_argument("-o", "--output", default=None,
                    help="Output path (default: stdout)")
    p.add_argument("--panel", default=DEFAULT_PANEL,
                    help=f"Panel to generate labels for (default: {DEFAULT_PANEL})")
    p.add_argument("--best-fit", action="store_true",
                    help="Pick the most common key per position across all panels")
    p.add_argument("--list-panels", action="store_true",
                    help="List all available panel names and exit")
    return p


def main(argv: Optional[List[str]] = None) -> int:
    args = build_parser().parse_args(argv)

    if args.list_panels:
        print("Available panels:")
        for name in GRID_PANELS:
            count = len(hk_groups.get(name, []))
            print(f"  {name} ({count} slots)")
        return 0

    if not args.files:
        print("Error: at least one .hkp file is required", file=sys.stderr)
        return 1

    result = generate(args.files, panel=args.panel, best_fit=args.best_fit)
    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(result, encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(result, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
